const STORAGE_KEY = 'laplateforme_presence_data';
const SESSION_KEY = 'laplateforme_presence_session';
const today = new Date();
const dateKey = (date) => date.toISOString().slice(0, 10);
const formatDate = (value, options = { day: 'numeric', month: 'short' }) => new Intl.DateTimeFormat('fr-FR', options).format(new Date(`${value}T12:00:00`));
const escapeHtml = (value) => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char]));

const seedRequests = [
    { id: 'r-1', userId: 'u-student', date: dateKey(new Date(today.getFullYear(), today.getMonth(), today.getDate() + 2)), status: 'pending' },
    { id: 'r-2', userId: 'u-moderator', date: dateKey(new Date(today.getFullYear(), today.getMonth(), today.getDate() + 4)), status: 'approved' },
    { id: 'r-3', userId: 'u-student', date: dateKey(new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7)), status: 'pending' }
];
let data = { users: [], requests: [] };
let session = null;

async function boot() {
    try {
        const response = await fetch('data/users.json');
        const seed = await response.json();
        const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null');
        data.users = saved?.users || seed.users;
        data.requests = saved?.requests || seedRequests;
    } catch (error) {
        data = { users: [], requests: [] };
        notify('Le fichier de données est indisponible.', 'danger');
    }
    session = JSON.parse(localStorage.getItem(SESSION_KEY) || 'null');
    bindEvents();
    render();
}
function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }
function setSession(user) { session = { userId: user.id }; localStorage.setItem(SESSION_KEY, JSON.stringify(session)); }
function currentUser() { return data.users.find((user) => user.id === session?.userId); }
function isMemberEmail(email) { return ['laplateforme.io', 'laplateforme.com'].includes(email.toLowerCase().split('@')[1]); }
function initials(name) { return name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase(); }
function notify(message, type = 'success') { document.getElementById('toast-container').innerHTML = `<div class="toast show border-0 text-bg-${type}" role="alert"><div class="d-flex"><div class="toast-body">${escapeHtml(message)}</div><button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"></button></div></div>`; setTimeout(() => document.querySelector('.toast')?.remove(), 3500); }
function bindEvents() {
    document.querySelectorAll('[data-auth-tab]').forEach((tab) => tab.addEventListener('click', () => switchAuth(tab.dataset.authTab)));
    document.getElementById('login-form').addEventListener('submit', login);
    document.getElementById('register-form').addEventListener('submit', register);
    document.addEventListener('click', (event) => {
        const route = event.target.closest('[data-route]')?.dataset.route;
        if (route) { event.preventDefault(); navigate(route); }
        const action = event.target.closest('[data-action]')?.dataset.action;
        if (action) handleAction(action, event.target.closest('[data-id]')?.dataset.id, event);
    });
}
function switchAuth(mode) { document.querySelectorAll('[data-auth-tab]').forEach((tab) => tab.classList.toggle('active', tab.dataset.authTab === mode)); document.getElementById('login-form').classList.toggle('d-none', mode !== 'login'); document.getElementById('register-form').classList.toggle('d-none', mode !== 'register'); }
function login(event) { event.preventDefault(); const email = document.getElementById('login-email').value.trim().toLowerCase(); const password = document.getElementById('login-password').value; const user = data.users.find((item) => item.email === email && item.password === password); if (!user) return notify('Adresse email ou mot de passe incorrect.', 'danger'); setSession(user); notify(`Bienvenue ${user.name.split(' ')[0]} !`); render(); }
function register(event) { event.preventDefault(); const name = document.getElementById('register-name').value.trim(); const email = document.getElementById('register-email').value.trim().toLowerCase(); const password = document.getElementById('register-password').value; if (!isMemberEmail(email)) return notify('Utilisez une adresse @laplateforme.io ou @laplateforme.com.', 'danger'); if (data.users.some((user) => user.email === email)) return notify('Cette adresse est déjà inscrite.', 'danger'); const user = { id: `u-${Date.now()}`, name, email, password, role: 'student' }; data.users.push(user); persist(); setSession(user); notify('Votre compte a bien été créé.'); render(); }
function logout() { localStorage.removeItem(SESSION_KEY); session = null; render(); }
function navigate(route) { if (!session) return; document.querySelectorAll('.app-page').forEach((page) => page.classList.add('d-none')); document.getElementById(`${route}-page`)?.classList.remove('d-none'); document.querySelectorAll('[data-route]').forEach((link) => link.classList.toggle('active', link.dataset.route === route)); document.getElementById('page-title').textContent = route === 'dashboard' ? `Bonjour ${currentUser().name.split(' ')[0]}.` : ({ calendar: 'Calendrier', moderation: 'Modération', admin: 'Gestion des droits' }[route] || 'Mon espace'); document.getElementById('page-subtitle').textContent = ({ dashboard: 'Gérez vos journées sur le campus.', calendar: 'Demandez une autorisation de présence.', moderation: 'Répondez aux demandes des étudiants.', admin: 'Gérez les accès à la plateforme.' }[route]); if (route === 'calendar') renderCalendar(); if (route === 'moderation') renderModeration(); if (route === 'admin') renderAdmin(); }
function render() { const user = currentUser(); document.getElementById('auth-view').classList.toggle('d-none', Boolean(user)); document.getElementById('app-view').classList.toggle('d-none', !user); if (!user) return; document.getElementById('today-label').textContent = new Intl.DateTimeFormat('fr-FR', { weekday: 'long', day: 'numeric', month: 'long' }).format(today); document.getElementById('nav-links').innerHTML = `<a class="nav-link active" href="#dashboard" data-route="dashboard">Tableau de bord</a><a class="nav-link" href="#calendar" data-route="calendar">Mon calendrier</a>${['moderator', 'admin'].includes(user.role) ? '<a class="nav-link" href="#moderation" data-route="moderation">Modération</a>' : ''}${user.role === 'admin' ? '<a class="nav-link" href="#admin" data-route="admin">Droits</a>' : ''}<button class="btn btn-sm btn-outline-teal ms-lg-2" data-action="logout">Déconnexion</button>`; renderDashboard(); navigate('dashboard'); }
function userRequests(userId = currentUser().id) { return data.requests.filter((request) => request.userId === userId); }
function statusLabel(status) { return { pending: 'En attente', approved: 'Acceptée', rejected: 'Refusée' }[status]; }
function requestLine(request) { const user = data.users.find((item) => item.id === request.userId); return `<div class="request-row"><div class="person-info"><span class="avatar">${initials(user.name)}</span><div><strong>${formatDate(request.date, { weekday: 'long', day: 'numeric', month: 'long' })}</strong><small>${request.status === 'approved' ? 'Votre présence est confirmée' : 'Réponse de l’équipe attendue'}</small></div></div><span class="status ${request.status}">${statusLabel(request.status)}</span></div>`; }
function renderDashboard() { const user = currentUser(); const requests = userRequests(); const approved = requests.filter((request) => request.status === 'approved').length; const pending = requests.filter((request) => request.status === 'pending').length; document.getElementById('dashboard-page').innerHTML = `<div class="stat-grid"><div class="stat-card"><span class="stat-icon"><i class="bi bi-calendar-check"></i></span><div><div class="stat-value">${approved}</div><div class="stat-label">Journées confirmées</div></div></div><div class="stat-card"><span class="stat-icon"><i class="bi bi-hourglass-split"></i></span><div><div class="stat-value">${pending}</div><div class="stat-label">Demandes en attente</div></div></div><div class="stat-card"><span class="stat-icon"><i class="bi bi-people"></i></span><div><div class="stat-value">${data.users.length}</div><div class="stat-label">Membres inscrits</div></div></div></div><div class="dashboard-grid"><div class="panel"><div class="panel-heading"><h3>Mes prochaines présences</h3><a href="#calendar" data-route="calendar">Voir le calendrier <i class="bi bi-arrow-right"></i></a></div>${requests.length ? requests.sort((a, b) => a.date.localeCompare(b.date)).map(requestLine).join('') : '<div class="empty-state"><i class="bi bi-calendar2-plus"></i>Aucune demande pour le moment.</div>'}</div><div class="panel"><div class="panel-heading"><h3>À retenir</h3></div><div class="empty-state"><i class="bi bi-lightbulb"></i><strong>Les demandes sont modifiables jusqu’à la veille.</strong><br>Après le passage de la date, la décision est définitive.</div></div></div>`; }
function monthDays() { const year = today.getFullYear(); const month = today.getMonth(); const first = new Date(year, month, 1); const last = new Date(year, month + 1, 0); const start = (first.getDay() + 6) % 7; const days = []; for (let index = 0; index < start; index += 1) days.push({ muted: true }); for (let day = 1; day <= last.getDate(); day += 1) days.push({ date: dateKey(new Date(year, month, day)), day }); while (days.length % 7) days.push({ muted: true }); return days; }
function renderCalendar() { const requests = userRequests(); const cells = monthDays().map((cell) => { if (cell.muted) return '<div class="day muted"></div>'; const date = new Date(`${cell.date}T12:00:00`); const past = date < new Date(dateKey(today)); const request = requests.find((item) => item.date === cell.date); return `<div class="day ${past ? 'past' : ''} ${cell.date === dateKey(today) ? 'today' : ''}" data-action="toggle-request" data-id="${cell.date}" title="${past ? 'Date passée' : request ? 'Cliquer pour modifier' : 'Cliquer pour demander'}"><span class="day-number">${cell.day}</span>${request ? `<span class="day-request ${request.status}">${statusLabel(request.status)}</span>` : ''}</div>`; }).join(''); document.getElementById('calendar-page').innerHTML = `<div class="panel"><div class="calendar-toolbar"><button class="btn btn-sm btn-outline-teal" data-route="dashboard"><i class="bi bi-arrow-left"></i> Retour</button><h2>${new Intl.DateTimeFormat('fr-FR', { month: 'long', year: 'numeric' }).format(today)}</h2><span class="small text-muted">Cliquez sur une date future</span></div><div class="calendar-wrap"><div class="calendar-grid"><div class="weekday">Lun</div><div class="weekday">Mar</div><div class="weekday">Mer</div><div class="weekday">Jeu</div><div class="weekday">Ven</div><div class="weekday">Sam</div><div class="weekday">Dim</div>${cells}</div></div></div>`; }
function toggleRequest(date) { if (new Date(`${date}T12:00:00`) < new Date(dateKey(today))) return notify('Une date passée ne peut plus être modifiée.', 'danger'); const existing = data.requests.find((request) => request.userId === currentUser().id && request.date === date); if (existing) { if (existing.status !== 'pending') return notify('Une demande traitée ne peut plus être modifiée.', 'danger'); data.requests = data.requests.filter((request) => request !== existing); notify('Votre demande a été annulée.'); } else { data.requests.push({ id: `r-${Date.now()}`, userId: currentUser().id, date, status: 'pending' }); notify('Demande envoyée à l’équipe.'); } persist(); renderCalendar(); renderDashboard(); }
function renderModeration() { const visible = data.requests.filter((request) => request.status === 'pending' || currentUser().role === 'admin'); document.getElementById('moderation-page').innerHTML = `<div class="panel"><div class="panel-heading"><h3>Demandes de présence</h3><span class="status pending">${data.requests.filter((request) => request.status === 'pending').length} en attente</span></div><div class="table-responsive"><table class="table"><thead><tr><th>Étudiant</th><th>Date demandée</th><th>Statut</th><th class="text-end">Décision</th></tr></thead><tbody>${visible.length ? visible.sort((a, b) => a.date.localeCompare(b.date)).map((request) => { const user = data.users.find((item) => item.id === request.userId); return `<tr><td><div class="person-info"><span class="avatar">${initials(user.name)}</span><div><strong>${escapeHtml(user.name)}</strong><small>${escapeHtml(user.email)}</small></div></div></td><td>${formatDate(request.date, { weekday: 'long', day: 'numeric', month: 'long' })}</td><td><span class="status ${request.status}">${statusLabel(request.status)}</span></td><td class="text-end">${request.status === 'pending' ? `<button class="btn btn-sm btn-outline-teal me-1" data-action="approve" data-id="${request.id}" title="Accepter"><i class="bi bi-check-lg"></i></button><button class="btn btn-sm btn-outline-danger" data-action="reject" data-id="${request.id}" title="Refuser"><i class="bi bi-x-lg"></i></button>` : '<span class="text-muted small">Décision enregistrée</span>'}</td></tr>`; }).join('') : '<tr><td colspan="4"><div class="empty-state"><i class="bi bi-check2-circle"></i>Aucune demande à afficher.</div></td></tr>'}</tbody></table></div></div>`; }
function renderAdmin() { document.getElementById('admin-page').innerHTML = `<div class="panel"><div class="panel-heading"><h3>Membres et droits d’accès</h3><span class="small text-muted">${data.users.length} comptes</span></div><div class="table-responsive"><table class="table"><thead><tr><th>Membre</th><th>Rôle actuel</th><th class="text-end">Modifier</th></tr></thead><tbody>${data.users.map((user) => `<tr><td><div class="person-info"><span class="avatar">${initials(user.name)}</span><div><strong>${escapeHtml(user.name)}</strong><small>${escapeHtml(user.email)}</small></div></div></td><td><span class="status ${user.role === 'student' ? 'pending' : 'approved'}">${user.role === 'student' ? 'Étudiant' : user.role === 'moderator' ? 'Modérateur' : 'Administrateur'}</span></td><td class="text-end"><select class="role-select" data-action="change-role" data-id="${user.id}" aria-label="Changer le rôle de ${escapeHtml(user.name)}"><option value="student" ${user.role === 'student' ? 'selected' : ''}>Étudiant</option><option value="moderator" ${user.role === 'moderator' ? 'selected' : ''}>Modérateur</option><option value="admin" ${user.role === 'admin' ? 'selected' : ''}>Administrateur</option></select></td></tr>`).join('')}</tbody></table></div></div>`; }
function handleAction(action, id, event) { if (action === 'logout') return logout(); if (action === 'toggle-request') return toggleRequest(id); if (action === 'approve' || action === 'reject') { const request = data.requests.find((item) => item.id === id); if (request) { request.status = action === 'approve' ? 'approved' : 'rejected'; persist(); renderModeration(); renderDashboard(); notify(action === 'approve' ? 'Présence acceptée.' : 'Présence refusée.'); } } if (action === 'change-role') { const user = data.users.find((item) => item.id === id); if (user && event.target.value) { user.role = event.target.value; persist(); notify('Rôle mis à jour.'); renderAdmin(); render(); } } }
boot();
